import { 
  User, 
  Organization, 
  Campus, 
  Membership, 
  ChurchEvent, 
  Task, 
  ActivityLog, 
  DemandTypeDefinition,
  EventTemplate
} from '../types';

export const DEMAND_TYPES: DemandTypeDefinition[] = [
  {
    type: 'ARTE',
    label: 'Criar uma Arte / Design',
    icon: 'Palette',
    description: 'Post simples, convite, avatar, flyer digital ou criativo para mídias.',
    color: 'text-indigo-400 border-indigo-500/30 bg-indigo-500/10',
    bgLight: 'hover:bg-indigo-950/40 hover:border-indigo-500/60',
    placeholderText: 'Ex: Arte para divulgação do retiro de casais no Instagram...',
  },
  {
    type: 'VIDEO',
    label: 'Produzir um Vídeo / Teaser',
    icon: 'Video',
    description: 'Captação, gravação em estúdio, edição de cortes, reels ou vinheta.',
    color: 'text-rose-400 border-rose-500/30 bg-rose-500/10',
    bgLight: 'hover:bg-rose-950/40 hover:border-rose-500/60',
    placeholderText: 'Ex: Vídeo de 60s convidando para a Conferência de Jovens...',
  },
  {
    type: 'SOCIAL_MEDIA',
    label: 'Divulgação / Social Media',
    icon: 'Share2',
    description: 'Carrossel de conteúdo, stories, calendário semanal de publicações.',
    color: 'text-purple-400 border-purple-500/30 bg-purple-500/10',
    bgLight: 'hover:bg-purple-950/40 hover:border-purple-500/60',
    placeholderText: 'Ex: Carrossel com resumo dos pontos da mensagem de domingo...',
  },
  {
    type: 'FOTOGRAFIA',
    label: 'Cobertura de Foto / Culto',
    icon: 'Camera',
    description: 'Escala de fotógrafos para batismo, culto especial ou evento.',
    color: 'text-cyan-400 border-cyan-500/30 bg-cyan-500/10',
    bgLight: 'hover:bg-cyan-950/40 hover:border-cyan-500/60',
    placeholderText: 'Ex: Cobertura fotográfica da Cantata de Natal no auditório...',
  },
  {
    type: 'IMPRESSAO',
    label: 'Solicitar Impressão / Gráfica',
    icon: 'Printer',
    description: 'Banners, panfletos, pulseiras, credenciais, carnês ou envelopes.',
    color: 'text-amber-400 border-amber-500/30 bg-amber-500/10',
    bgLight: 'hover:bg-amber-950/40 hover:border-amber-500/60',
    placeholderText: 'Ex: 2 Banners roll-up 200x80cm para o saguão principal...',
  },
  {
    type: 'TEXTO',
    label: 'Solicitar Texto / Copywriting',
    icon: 'FileText',
    description: 'Roteiro pastoral, comunicado oficial, legenda ou artigo devocional.',
    color: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10',
    bgLight: 'hover:bg-emerald-950/40 hover:border-emerald-500/60',
    placeholderText: 'Ex: Carta aos membros sobre a nova campanha de missões...',
  },
  {
    type: 'APRESENTACAO',
    label: 'Telão LED / Slides Culto',
    icon: 'Tv',
    description: 'Slides de avisos, fundo dinâmico, letras de louvor ou vinheta de abertura.',
    color: 'text-blue-400 border-blue-500/30 bg-blue-500/10',
    bgLight: 'hover:bg-blue-950/40 hover:border-blue-500/60',
    placeholderText: 'Ex: Slides de avisos de dízimos e ofertas em 1920x1080...',
  },
  {
    type: 'SITE',
    label: 'Site / Landing Page',
    icon: 'Globe',
    description: 'Página de inscrições, atualização de banner no portal ou formulário.',
    color: 'text-teal-400 border-teal-500/30 bg-teal-500/10',
    bgLight: 'hover:bg-teal-950/40 hover:border-teal-500/60',
    placeholderText: 'Ex: Página de venda de ingressos do Acampamento de Verão...',
  },
  {
    type: 'COMUNICACAO_INTERNA',
    label: 'Comunicação Interna',
    icon: 'Megaphone',
    description: 'Mensagens no WhatsApp da liderança, avisos no púlpito ou e-mail interno.',
    color: 'text-orange-400 border-orange-500/30 bg-orange-500/10',
    bgLight: 'hover:bg-orange-950/40 hover:border-orange-500/60',
    placeholderText: 'Ex: Comunicado aos voluntários sobre o horário de passagem de som...',
  },
  {
    type: 'EVENTO',
    label: 'Produção Completa de Evento',
    icon: 'Calendar',
    description: 'Campanha integrada com artes, telões, camisetas, impressos e mídias.',
    color: 'text-pink-400 border-pink-500/30 bg-pink-500/10',
    bgLight: 'hover:bg-pink-950/40 hover:border-pink-500/60',
    placeholderText: 'Ex: Pacote de comunicação para conferência de 3 dias...',
  },
  {
    type: 'OUTRO',
    label: 'Outra Demanda Especial',
    icon: 'Package',
    description: 'Qualquer outra necessidade da equipe de comunicação da igreja.',
    color: 'text-slate-400 border-slate-500/30 bg-slate-500/10',
    bgLight: 'hover:bg-slate-950/60 hover:border-slate-500/60',
    placeholderText: 'Descreva detalhadamente a necessidade especial...',
  },
];

// --- EVENT TEMPLATES (Gerar projeto a partir de modelo) ---
export const EVENT_TEMPLATES: EventTemplate[] = [
  {
    id: 'tmpl_conferencia',
    name: 'Conferência / Congresso Anual',
    category: 'CONFERENCIA',
    description: 'Pacote completo de 10 entregas encadeadas para grandes conferências (identidade, landing page, vídeos, telões e cobertura).',
    defaultTasks: [
      {
        title: 'Identidade Visual & Key Visual do Tema',
        demandType: 'ARTE',
        daysBeforeEvent: 45,
        durationDays: 7,
        priority: 'HIGH',
        checklist: ['Paleta de cores e tipografia', 'Logo da conferência', 'Manual de aplicação'],
      },
      {
        title: 'Landing Page de Inscrições & Lotes',
        demandType: 'SITE',
        daysBeforeEvent: 40,
        durationDays: 5,
        priority: 'HIGH',
        checklist: ['Integração com gateway de pagamento', 'Informações de preletores', 'FAQ e cronograma'],
        dependsOnIndex: 0,
      },
      {
        title: 'Roteiro & Produção do Vídeo Teaser Oficial',
        demandType: 'VIDEO',
        daysBeforeEvent: 35,
        durationDays: 8,
        priority: 'URGENT',
        checklist: ['Gravação em estúdio com preletores', 'Edição cinematográfica', 'Mixagem de áudio'],
        dependsOnIndex: 0,
      },
      {
        title: 'Campanha de Lançamento no Instagram (Carrossel)',
        demandType: 'SOCIAL_MEDIA',
        daysBeforeEvent: 30,
        durationDays: 3,
        priority: 'HIGH',
        checklist: ['Carrossel 4:5', 'Stories de contagem regressiva', 'Link na bio'],
        dependsOnIndex: 0,
      },
      {
        title: 'Vinheta 3D e Telão LED de Abertura',
        demandType: 'APRESENTACAO',
        daysBeforeEvent: 15,
        durationDays: 5,
        priority: 'HIGH',
        checklist: ['Resolução 3840x1080', 'Loop de fundo para louvor'],
        dependsOnIndex: 2,
      },
      {
        title: 'Pulseiras, Credenciais e Banners de Recepção',
        demandType: 'IMPRESSAO',
        daysBeforeEvent: 12,
        durationDays: 4,
        priority: 'MEDIUM',
        checklist: ['Arquivo em CMYK', 'Envio para gráfica'],
        dependsOnIndex: 0,
      },
      {
        title: 'Escala de Fotografia e Cobertura em Tempo Real',
        demandType: 'FOTOGRAFIA',
        daysBeforeEvent: 3,
        durationDays: 2,
        priority: 'MEDIUM',
        checklist: ['Briefing dos fotógrafos', 'Upload diário no Drive para stories'],
      },
      {
        title: 'Vídeo Aftermovie & Pós-Conferência',
        demandType: 'VIDEO',
        daysBeforeEvent: 0, // Day of event + aftermath
        durationDays: 3,
        priority: 'MEDIUM',
        checklist: ['Seleção dos melhores momentos', 'Depoimentos de participantes'],
      },
    ],
  },
  {
    id: 'tmpl_culto_especial',
    name: 'Culto Especial / Batismo',
    category: 'CULTO',
    description: 'Fluxo ágil de 5 entregas para cultos comemorativos, batismos e santa ceia.',
    defaultTasks: [
      {
        title: 'Arte Principal de Divulgação',
        demandType: 'ARTE',
        daysBeforeEvent: 14,
        durationDays: 3,
        priority: 'HIGH',
        checklist: ['Post feed 1:1 e 4:5', 'Stories format 9:16'],
      },
      {
        title: 'Slides para Telão LED e Avisos',
        demandType: 'APRESENTACAO',
        daysBeforeEvent: 7,
        durationDays: 2,
        priority: 'MEDIUM',
        checklist: ['Slides de avisos 16:9', 'Orientações para os membros'],
        dependsOnIndex: 0,
      },
      {
        title: 'Escala de Fotógrafos para o Culto',
        demandType: 'FOTOGRAFIA',
        daysBeforeEvent: 4,
        durationDays: 1,
        priority: 'MEDIUM',
        checklist: ['Fotógrafos escalados no saguão e batistério'],
      },
      {
        title: 'Vídeo Resumo de Melhores Momentos (Reels)',
        demandType: 'VIDEO',
        daysBeforeEvent: 0,
        durationDays: 2,
        priority: 'MEDIUM',
        checklist: ['Edição vertical 9:16', 'Legendas dinâmicas'],
      },
    ],
  },
  {
    id: 'tmpl_serie_mensagens',
    name: 'Série de Sermões (4 Semanas)',
    category: 'SERIE',
    description: 'Campanha temática para séries ministeriais dominicais.',
    defaultTasks: [
      {
        title: 'Identidade Visual & Key Visual da Série',
        demandType: 'ARTE',
        daysBeforeEvent: 20,
        durationDays: 4,
        priority: 'HIGH',
        checklist: ['Paleta visual', 'Versículo chave'],
      },
      {
        title: 'Vinheta de Abertura para Telão do Altar',
        demandType: 'APRESENTACAO',
        daysBeforeEvent: 12,
        durationDays: 3,
        priority: 'HIGH',
        checklist: ['Vídeo de 20s para introdução da pregação'],
        dependsOnIndex: 0,
      },
      {
        title: 'Guia de Estudo / Devocional em PDF',
        demandType: 'TEXTO',
        daysBeforeEvent: 10,
        durationDays: 4,
        priority: 'MEDIUM',
        checklist: ['Perguntas para grupos pequenos', 'Diagramação'],
        dependsOnIndex: 0,
      },
      {
        title: 'Carrossel Semanal com Frases da Mensagem',
        demandType: 'SOCIAL_MEDIA',
        daysBeforeEvent: 0,
        durationDays: 2,
        priority: 'MEDIUM',
        checklist: ['Extração das melhores citações do pastor'],
      },
    ],
  },
];

// --- ORGANIZATIONS (TENANTS) ---
export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org_ibm',
    name: 'Igreja Batista Memorial',
    slug: 'ibm',
    branding: {
      primaryColor: '#4f46e5',
      secondaryColor: '#818cf8',
      logoUrl: 'https://images.unsplash.com/photo-1548625361-195fe5707746?w=150&auto=format&fit=crop&q=80',
    },
    subscription: {
      organizationId: 'org_ibm',
      plan: 'PRO',
      status: 'ACTIVE',
      currentPeriodStart: '2026-01-01T00:00:00Z',
      currentPeriodEnd: '2027-01-01T00:00:00Z',
      provider: 'STRIPE',
    },
    limits: {
      maxMembers: 50,
      maxCampuses: 10,
      maxEvents: 100,
      maxTasks: 1000,
      storageGB: 50,
      customBranding: true,
      advancedReports: true,
      gantt: true,
      apiAccess: true,
    },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'org_comunidade',
    name: 'Comunidade da Fé',
    slug: 'comunidade-fe',
    branding: {
      primaryColor: '#0d9488',
      secondaryColor: '#2dd4bf',
      logoUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?w=150&auto=format&fit=crop&q=80',
    },
    subscription: {
      organizationId: 'org_comunidade',
      plan: 'STARTER',
      status: 'ACTIVE',
      currentPeriodStart: '2026-02-01T00:00:00Z',
      currentPeriodEnd: '2027-02-01T00:00:00Z',
    },
    limits: {
      maxMembers: 15,
      maxCampuses: 2,
      maxEvents: 20,
      maxTasks: 200,
      storageGB: 10,
      customBranding: true,
      advancedReports: false,
      gantt: true,
      apiAccess: false,
    },
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
];

// --- CAMPUSES ---
export const INITIAL_CAMPUSES: Campus[] = [
  {
    id: 'camp_ibm_sede',
    organizationId: 'org_ibm',
    name: 'Sede (Auditório Principal)',
    code: 'SEDE',
    city: 'São Paulo - SP',
    address: 'Av. Paulista, 1000 - Bela Vista',
    isMainCampus: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'camp_ibm_alpha',
    organizationId: 'org_ibm',
    name: 'Campus Alphaville',
    code: 'ALPHA',
    city: 'Barueri - SP',
    address: 'Al. Rio Negro, 500 - Alphaville',
    isMainCampus: false,
    createdAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'camp_ibm_centro',
    organizationId: 'org_ibm',
    name: 'Campus Centro Histórico',
    code: 'CENTRO',
    city: 'São Paulo - SP',
    address: 'R. da Consolação, 250 - Centro',
    isMainCampus: false,
    createdAt: '2026-04-15T00:00:00Z',
  },
  {
    id: 'camp_com_zs',
    organizationId: 'org_comunidade',
    name: 'Campus Zona Sul',
    code: 'ZS',
    city: 'São Paulo - SP',
    address: 'Av. Santo Amaro, 2200',
    isMainCampus: true,
    createdAt: '2026-02-01T00:00:00Z',
  },
];

// --- GLOBAL USERS ---
export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin',
    name: 'Pr. Carlos Mendes',
    email: 'admin@marketingibm.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '(11) 98765-4321',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'usr_leader',
    name: 'Mariana Lima',
    email: 'mariana.lima@marketingibm.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    phone: '(11) 97654-3210',
    createdAt: '2026-01-12T14:30:00Z',
  },
  {
    id: 'usr_team_lucas',
    name: 'Lucas Andrade',
    email: 'lucas.design@marketingibm.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '(11) 96543-2109',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'usr_team_beatriz',
    name: 'Beatriz Santos',
    email: 'beatriz.social@marketingibm.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    phone: '(11) 95432-1098',
    createdAt: '2026-01-18T11:20:00Z',
  },
  {
    id: 'usr_requester_tiago',
    name: 'Pr. Tiago Rocha',
    email: 'tiago.jovens@marketingibm.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '(11) 94321-0987',
    createdAt: '2026-02-01T16:00:00Z',
  },
];

// --- MEMBERSHIPS ---
export const INITIAL_MEMBERSHIPS: Membership[] = [
  {
    id: 'mem_carlos_ibm',
    userId: 'usr_admin',
    organizationId: 'org_ibm',
    hasOrgWideAccess: true,
    campusIds: [],
    role: 'ADMIN',
    department: 'Direção Geral & Pastoral',
    status: 'ACTIVE',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'mem_mariana_ibm',
    userId: 'usr_leader',
    organizationId: 'org_ibm',
    hasOrgWideAccess: false,
    campusIds: ['camp_ibm_sede', 'camp_ibm_alpha'],
    role: 'LEADER',
    department: 'Coordenação de Marketing & Mídias',
    status: 'ACTIVE',
    createdAt: '2026-01-12T14:30:00Z',
    updatedAt: '2026-01-12T14:30:00Z',
  },
  {
    id: 'mem_lucas_ibm',
    userId: 'usr_team_lucas',
    organizationId: 'org_ibm',
    hasOrgWideAccess: false,
    campusIds: ['camp_ibm_sede'],
    role: 'TEAM',
    department: 'Design Gráfico & Telões',
    status: 'ACTIVE',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'mem_beatriz_ibm',
    userId: 'usr_team_beatriz',
    organizationId: 'org_ibm',
    hasOrgWideAccess: false,
    campusIds: ['camp_ibm_sede', 'camp_ibm_centro'],
    role: 'TEAM',
    department: 'Social Media & Copywriting',
    status: 'ACTIVE',
    createdAt: '2026-01-18T11:20:00Z',
    updatedAt: '2026-01-18T11:20:00Z',
  },
  {
    id: 'mem_tiago_ibm',
    userId: 'usr_requester_tiago',
    organizationId: 'org_ibm',
    hasOrgWideAccess: false,
    campusIds: ['camp_ibm_alpha'],
    role: 'LEADER',
    department: 'Ministério de Jovens - Alphaville',
    status: 'ACTIVE',
    createdAt: '2026-02-01T16:00:00Z',
    updatedAt: '2026-02-01T16:00:00Z',
  },
  {
    id: 'mem_tiago_comunidade',
    userId: 'usr_requester_tiago',
    organizationId: 'org_comunidade',
    hasOrgWideAccess: true,
    campusIds: [],
    role: 'ADMIN',
    department: 'Diretoria Pastoral',
    status: 'ACTIVE',
    createdAt: '2026-02-05T10:00:00Z',
    updatedAt: '2026-02-05T10:00:00Z',
  },
];

// --- EVENTS ---
export const INITIAL_EVENTS: ChurchEvent[] = [
  {
    id: 'evt_aviva_2026',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_sede',
    campusName: 'Sede (Auditório Principal)',
    title: 'Conferência Aviva 2026',
    description: 'Grande conferência anual de adoração e avivamento com preletores convidados e vigília jovem.',
    category: 'CONFERENCIA',
    startDate: '2026-09-18',
    endDate: '2026-09-20',
    location: 'Templo Principal IBM & Transmissão Online',
    leaderId: 'usr_leader',
    leaderName: 'Mariana Lima',
    teamIds: ['usr_team_lucas', 'usr_team_beatriz', 'usr_requester_tiago'],
    status: 'IN_PROGRESS',
    isArchived: false,
    bannerColor: 'from-indigo-600 to-purple-600',
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-20T15:00:00Z',
  },
  {
    id: 'evt_familia_altar',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_sede',
    campusName: 'Sede (Auditório Principal)',
    title: 'Série de Mensagens: Família no Altar',
    description: 'Campanha de 4 semanas aos domingos focada na edificação dos lares, casamentos e filhos.',
    category: 'SERIE',
    startDate: '2026-09-01',
    endDate: '2026-09-27',
    location: 'Todos os Cultos Dominicais (09h e 18h)',
    leaderId: 'usr_admin',
    leaderName: 'Pr. Carlos Mendes',
    teamIds: ['usr_team_lucas', 'usr_team_beatriz'],
    status: 'PLANNING',
    isArchived: false,
    bannerColor: 'from-blue-600 to-cyan-600',
    createdAt: '2026-08-10T11:00:00Z',
    updatedAt: '2026-08-22T09:30:00Z',
  },
  {
    id: 'evt_alpha_inauguracao',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_alpha',
    campusName: 'Campus Alphaville',
    title: 'Culto de Celebração de 1 Ano - Alphaville',
    description: 'Comemoração de 1 ano de implantação do campus Alphaville com batismos e comunhão.',
    category: 'CULTO',
    startDate: '2026-09-12',
    endDate: '2026-09-12',
    location: 'Auditório Alphaville',
    leaderId: 'usr_requester_tiago',
    leaderName: 'Pr. Tiago Rocha',
    teamIds: ['usr_team_lucas'],
    status: 'PLANNING',
    isArchived: false,
    bannerColor: 'from-amber-600 to-orange-600',
    createdAt: '2026-08-15T14:00:00Z',
    updatedAt: '2026-08-23T18:00:00Z',
  },
  {
    id: 'evt_comunidade_conferencia',
    organizationId: 'org_comunidade',
    campusId: 'camp_com_zs',
    campusName: 'Campus Zona Sul',
    title: 'Conferência Fé e Esperança',
    description: 'Encontro anual de ministérios e lideranças da Comunidade da Fé.',
    category: 'CONFERENCIA',
    startDate: '2026-10-10',
    endDate: '2026-10-12',
    location: 'Sede Zona Sul',
    leaderId: 'usr_requester_tiago',
    leaderName: 'Pr. Tiago Rocha',
    teamIds: ['usr_requester_tiago'],
    status: 'IN_PROGRESS',
    isArchived: false,
    bannerColor: 'from-teal-600 to-emerald-600',
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-20T12:00:00Z',
  },
];

// --- TASKS ---
export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk_101',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_sede',
    campusName: 'Sede',
    title: 'Identidade Visual & Guia de Estilo - Aviva 2026',
    description: 'Criação da paleta de cores oficial, tipografia, logotipo e manual de aplicação para telões e redes sociais.',
    status: 'DONE',
    priority: 'HIGH',
    demandType: 'ARTE',
    eventId: 'evt_aviva_2026',
    eventName: 'Conferência Aviva 2026',
    requesterId: 'usr_leader',
    requesterName: 'Mariana Lima',
    assigneeId: 'usr_team_lucas',
    assigneeName: 'Lucas Andrade',
    assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    approverId: 'usr_admin',
    approverName: 'Pr. Carlos Mendes',
    requestedAt: '2026-08-08T10:00:00Z',
    startDate: '2026-08-10',
    deadline: '2026-08-18',
    completedAt: '2026-08-18T17:00:00Z',
    effortEstimate: '16h (2 dias)',
    tags: ['Identidade Visual', 'Design', 'Branding'],
    attachmentLinks: [
      {
        id: 'att_1',
        title: 'Manual de Identidade Visual - Canva',
        url: 'https://canva.com/design/example-aviva',
        type: 'canva',
      },
      {
        id: 'att_2',
        title: 'Assets em Alta Resolução - Google Drive',
        url: 'https://drive.google.com/drive/folders/aviva-assets',
        type: 'drive',
      }
    ],
    dependencies: [],
    checklist: [
      { id: 'chk_1', text: 'Definição de tipografia principal e secundária', completed: true },
      { id: 'chk_2', text: 'Criação de paleta cromática CMYK e RGB', completed: true },
      { id: 'chk_3', text: 'Aprovação com a liderança pastoral', completed: true },
    ],
    commentsCount: 3,
    isArchived: false,
    createdBy: 'usr_leader',
    createdByName: 'Mariana Lima',
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-08-18T17:00:00Z',
  },
  {
    id: 'tsk_102',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_sede',
    campusName: 'Sede',
    title: 'Roteiro e Copywriting para Vídeo Teaser de Lançamento',
    description: 'Escrever roteiro de 60 segundos focado no tema da conferência para gravação dos pastores.',
    status: 'DONE',
    priority: 'HIGH',
    demandType: 'TEXTO',
    eventId: 'evt_aviva_2026',
    eventName: 'Conferência Aviva 2026',
    requesterId: 'usr_leader',
    requesterName: 'Mariana Lima',
    assigneeId: 'usr_team_beatriz',
    assigneeName: 'Beatriz Santos',
    assigneeAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    approverId: 'usr_leader',
    approverName: 'Mariana Lima',
    requestedAt: '2026-08-15T10:00:00Z',
    startDate: '2026-08-16',
    deadline: '2026-08-22',
    completedAt: '2026-08-22T14:30:00Z',
    effortEstimate: '6h',
    tags: ['Copywriting', 'Vídeo', 'Roteiro'],
    attachmentLinks: [
      {
        id: 'att_3',
        title: 'Documento de Roteiro - Google Docs',
        url: 'https://docs.google.com/document/d/roteiro-aviva',
        type: 'document',
      }
    ],
    dependencies: ['tsk_101'],
    checklist: [
      { id: 'chk_4', text: 'Brainstorm com Pr. Carlos', completed: true },
      { id: 'chk_5', text: 'Validação de chamadas para ação (CTA)', completed: true },
    ],
    commentsCount: 2,
    isArchived: false,
    createdBy: 'usr_leader',
    createdByName: 'Mariana Lima',
    createdAt: '2026-08-16T10:00:00Z',
    updatedAt: '2026-08-22T14:30:00Z',
  },
  {
    id: 'tsk_103',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_sede',
    campusName: 'Sede',
    title: 'Captação e Edição do Vídeo Teaser Oficial',
    description: 'Gravação em estúdio com iluminação dramática, edição de áudio, trilha sonora cinematográfica e color grading.',
    status: 'IN_PROGRESS',
    priority: 'URGENT',
    demandType: 'VIDEO',
    eventId: 'evt_aviva_2026',
    eventName: 'Conferência Aviva 2026',
    requesterId: 'usr_leader',
    requesterName: 'Mariana Lima',
    assigneeId: 'usr_team_lucas',
    assigneeName: 'Lucas Andrade',
    assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    approverId: 'usr_admin',
    approverName: 'Pr. Carlos Mendes',
    requestedAt: '2026-08-19T09:00:00Z',
    startDate: '2026-08-23',
    deadline: '2026-08-28',
    effortEstimate: '18h (3 dias)',
    tags: ['Vídeo', 'Edição', 'Teaser'],
    attachmentLinks: [
      {
        id: 'att_4',
        title: 'Gravações Brutas 4K - Google Drive',
        url: 'https://drive.google.com/drive/folders/raw-footage-aviva',
        type: 'drive',
      }
    ],
    dependencies: ['tsk_102'],
    checklist: [
      { id: 'chk_6', text: 'Gravação de voz e takes no estúdio IBM', completed: true },
      { id: 'chk_7', text: 'Corte preliminar de vídeo', completed: true },
      { id: 'chk_8', text: 'Mixagem sonora e efeitos sonoros', completed: false },
      { id: 'chk_9', text: 'Aprovação final com coordenação', completed: false },
    ],
    commentsCount: 4,
    isArchived: false,
    createdBy: 'usr_leader',
    createdByName: 'Mariana Lima',
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-24T12:00:00Z',
  },
  {
    id: 'tsk_104',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_sede',
    campusName: 'Sede',
    title: 'Carrossel Instagram: Lote Promocional da Conferência',
    description: 'Post carrossel de 7 lâminas apresentando data, preletores confirmados e link na bio.',
    status: 'REVIEW',
    priority: 'HIGH',
    demandType: 'SOCIAL_MEDIA',
    eventId: 'evt_aviva_2026',
    eventName: 'Conferência Aviva 2026',
    requesterId: 'usr_leader',
    requesterName: 'Mariana Lima',
    assigneeId: 'usr_team_beatriz',
    assigneeName: 'Beatriz Santos',
    assigneeAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    approverId: 'usr_leader',
    approverName: 'Mariana Lima',
    requestedAt: '2026-08-21T14:00:00Z',
    startDate: '2026-08-24',
    deadline: '2026-08-26',
    effortEstimate: '5h',
    tags: ['Instagram', 'Carrossel', 'Redes Sociais'],
    attachmentLinks: [
      {
        id: 'att_5',
        title: 'Prévias dos Criativos no Figma',
        url: 'https://figma.com/file/carrossel-aviva',
        type: 'figma',
      }
    ],
    dependencies: ['tsk_101'],
    checklist: [
      { id: 'chk_10', text: 'Redação da copy de todas as lâminas', completed: true },
      { id: 'chk_11', text: 'Exportação em 1080x1350px (formato 4:5)', completed: true },
      { id: 'chk_12', text: 'Revisão ortográfica e aprovação', completed: false },
    ],
    commentsCount: 1,
    isArchived: false,
    createdBy: 'usr_team_beatriz',
    createdByName: 'Beatriz Santos',
    createdAt: '2026-08-22T15:00:00Z',
    updatedAt: '2026-08-24T16:00:00Z',
  },
  {
    id: 'tsk_105',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_sede',
    campusName: 'Sede',
    title: 'Vinheta Telão em Loop e Cenografia Visual LED',
    description: 'Animação 3D do tema para rodar no painel de LED de 12 metros do palco durante a abertura e louvor.',
    status: 'BLOCKED',
    priority: 'HIGH',
    demandType: 'APRESENTACAO',
    eventId: 'evt_aviva_2026',
    eventName: 'Conferência Aviva 2026',
    requesterId: 'usr_leader',
    requesterName: 'Mariana Lima',
    assigneeId: 'usr_team_lucas',
    assigneeName: 'Lucas Andrade',
    assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    approverId: 'usr_leader',
    approverName: 'Mariana Lima',
    requestedAt: '2026-08-22T10:00:00Z',
    startDate: '2026-08-29',
    deadline: '2026-09-08',
    effortEstimate: '12h',
    blockedReason: 'Aguardando exportação dos elementos 3D do vídeo teaser',
    blockedActionRequiredBy: 'Lucas Andrade (Vídeo Teaser)',
    tags: ['Motion Graphics', 'Telão LED', 'Cenografia'],
    attachmentLinks: [],
    dependencies: ['tsk_103'],
    checklist: [
      { id: 'chk_13', text: 'Aguardar render final do vídeo teaser para reaproveitar elementos', completed: false },
      { id: 'chk_14', text: 'Testar resolução de 3840x1080 no software do telão', completed: false },
    ],
    commentsCount: 2,
    isArchived: false,
    createdBy: 'usr_leader',
    createdByName: 'Mariana Lima',
    createdAt: '2026-08-23T11:00:00Z',
    updatedAt: '2026-08-24T10:00:00Z',
  },
  {
    id: 'tsk_106',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_alpha',
    campusName: 'Campus Alphaville',
    title: 'Banner de Fachada e Convite Digital - Culto 1 Ano Alphaville',
    description: 'Criação de arte de boas-vindas para a fachada do campus e cards de WhatsApp para os membros convidarem amigos.',
    status: 'PLANNING',
    priority: 'HIGH',
    demandType: 'ARTE',
    eventId: 'evt_alpha_inauguracao',
    eventName: 'Culto de Celebração de 1 Ano - Alphaville',
    requesterId: 'usr_requester_tiago',
    requesterName: 'Pr. Tiago Rocha',
    assigneeId: 'usr_team_lucas',
    assigneeName: 'Lucas Andrade',
    assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    approverId: 'usr_requester_tiago',
    approverName: 'Pr. Tiago Rocha',
    requestedAt: '2026-08-20T08:00:00Z',
    startDate: '2026-08-25',
    deadline: '2026-09-05',
    effortEstimate: '6h',
    tags: ['Alphaville', 'Fachada', 'Comemoração'],
    attachmentLinks: [],
    dependencies: [],
    checklist: [
      { id: 'chk_21', text: 'Medição da lona da fachada (4x2m)', completed: true },
      { id: 'chk_22', text: 'Layout e aprovação pastoral', completed: false },
    ],
    commentsCount: 0,
    isArchived: false,
    createdBy: 'usr_requester_tiago',
    createdByName: 'Pr. Tiago Rocha',
    createdAt: '2026-08-21T08:30:00Z',
    updatedAt: '2026-08-23T16:00:00Z',
  },
  {
    id: 'tsk_107',
    organizationId: 'org_ibm',
    campusId: null,
    campusName: 'Toda a Organização (Geral)',
    title: 'Demanda de Nova Logo para Ministério de Jovens',
    description: 'Solicitação do Pr. Tiago para modernizar o logo do grupo "Juventude IBM" para aplicação em camisetas e stickers.',
    status: 'INBOX',
    priority: 'LOW',
    demandType: 'ARTE',
    requesterId: 'usr_requester_tiago',
    requesterName: 'Pr. Tiago Rocha',
    assigneeId: undefined,
    assigneeName: undefined,
    requestedAt: '2026-08-24T14:15:00Z',
    startDate: '2026-09-02',
    deadline: '2026-09-15',
    effortEstimate: '8h',
    tags: ['Institucional', 'Jovens', 'Logo'],
    attachmentLinks: [],
    dependencies: [],
    checklist: [],
    commentsCount: 1,
    isArchived: false,
    createdBy: 'usr_requester_tiago',
    createdByName: 'Pr. Tiago Rocha',
    createdAt: '2026-08-24T14:15:00Z',
    updatedAt: '2026-08-24T14:15:00Z',
  },
  {
    id: 'tsk_108',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_centro',
    campusName: 'Campus Centro Histórico',
    title: 'Artes Semanais para Telões de Avisos - Campus Centro',
    description: 'Slides com avisos de reuniões de oração e horários dos cultos da Consolação.',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    demandType: 'APRESENTACAO',
    requesterId: 'usr_leader',
    requesterName: 'Mariana Lima',
    assigneeId: 'usr_team_beatriz',
    assigneeName: 'Beatriz Santos',
    assigneeAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    approverId: 'usr_leader',
    approverName: 'Mariana Lima',
    requestedAt: '2026-08-24T08:30:00Z',
    startDate: '2026-08-24',
    deadline: '2026-08-28',
    effortEstimate: '4h',
    tags: ['Avisos', 'Centro', 'Culto'],
    attachmentLinks: [],
    dependencies: [],
    checklist: [
      { id: 'chk_18', text: 'Coletar avisos com a equipe do Centro', completed: true },
      { id: 'chk_19', text: 'Montar slides no formato 16:9', completed: true },
    ],
    commentsCount: 0,
    isArchived: false,
    createdBy: 'usr_leader',
    createdByName: 'Mariana Lima',
    createdAt: '2026-08-24T09:00:00Z',
    updatedAt: '2026-08-24T15:30:00Z',
  },
  {
    id: 'tsk_comunidade_1',
    organizationId: 'org_comunidade',
    campusId: 'camp_com_zs',
    campusName: 'Campus Zona Sul',
    title: 'Banner e Folder da Conferência Fé e Esperança',
    description: 'Material institucional para entrega no credenciamento da conferência.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    demandType: 'IMPRESSAO',
    eventId: 'evt_comunidade_conferencia',
    eventName: 'Conferência Fé e Esperança',
    requesterId: 'usr_requester_tiago',
    requesterName: 'Pr. Tiago Rocha',
    assigneeId: 'usr_requester_tiago',
    assigneeName: 'Pr. Tiago Rocha',
    requestedAt: '2026-08-20T10:00:00Z',
    startDate: '2026-08-22',
    deadline: '2026-09-10',
    effortEstimate: '10h',
    tags: ['Conferência', 'Impressão'],
    attachmentLinks: [],
    dependencies: [],
    checklist: [],
    commentsCount: 0,
    isArchived: false,
    createdBy: 'usr_requester_tiago',
    createdByName: 'Pr. Tiago Rocha',
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-08-22T10:00:00Z',
  }
];

export const INITIAL_COMMENTS = [
  {
    id: 'cmt_1',
    organizationId: 'org_ibm',
    taskId: 'tsk_101',
    userId: 'usr_leader',
    userName: 'Mariana Lima',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    userRole: 'LEADER' as const,
    content: 'Lucas, as cores ficaram maravilhosas! O Pr. Carlos aprovou a combinação oficial.',
    createdAt: '2026-08-18T11:00:00Z',
  },
  {
    id: 'cmt_2',
    organizationId: 'org_ibm',
    taskId: 'tsk_103',
    userId: 'usr_team_lucas',
    userName: 'Lucas Andrade',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    userRole: 'TEAM' as const,
    content: 'Gravações no estúdio IBM concluídas. Iniciando color grading cinematográfico.',
    createdAt: '2026-08-24T12:00:00Z',
  },
];

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act_1',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_sede',
    userId: 'usr_team_beatriz',
    userName: 'Beatriz Santos',
    action: 'moveu a tarefa',
    fieldChanged: 'status',
    oldValue: 'IN_PROGRESS',
    newValue: 'REVIEW',
    targetType: 'task',
    targetId: 'tsk_104',
    targetTitle: 'Carrossel Instagram: Lote Promocional da Conferência',
    timestamp: '2026-08-24T16:00:00Z',
  },
  {
    id: 'act_2',
    organizationId: 'org_ibm',
    campusId: 'camp_ibm_alpha',
    userId: 'usr_requester_tiago',
    userName: 'Pr. Tiago Rocha',
    action: 'abriu solicitação na Central de Demandas',
    targetType: 'demand',
    targetId: 'tsk_106',
    targetTitle: 'Banner de Fachada e Convite Digital - Culto 1 Ano Alphaville',
    timestamp: '2026-08-20T08:00:00Z',
  },
];
